# Temporary patch until we figure out the structure and contents of all resources
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./neptune.yaml
  - ../details/operator-sdk/config/unified-installer-script

patches:
  - path: ./operator-proxy-role.yaml
