apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: astra
  labels:
    control-plane: neptune-controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: neptune-controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: neptune
    app.kubernetes.io/part-of: neptune
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: neptune-controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: neptune-controller-manager
        app: controller.neptune.netapp.io
    spec:
      imagePullSecrets:
      - name: image-registry-creds
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        image: cr.netapp.astra.io/controller:60ab17f
        name: manager
        envFrom:
        - configMapRef:
            name: neptune-config
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1280Mi
          requests:
            cpu: 100m
            memory: 640Mi
      serviceAccountName: neptune-controller-manager
      terminationGracePeriodSeconds: 10
