//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 NetApp, Inc. All Rights Reserved.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Astra) DeepCopyInto(out *Astra) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Astra.
func (in *Astra) DeepCopy() *Astra {
	if in == nil {
		return nil
	}
	out := new(Astra)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AstraConnect) DeepCopyInto(out *AstraConnect) {
	*out = *in
	in.ResourceRequirements.DeepCopyInto(&out.ResourceRequirements)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AstraConnect.
func (in *AstraConnect) DeepCopy() *AstraConnect {
	if in == nil {
		return nil
	}
	out := new(AstraConnect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AstraConnector) DeepCopyInto(out *AstraConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AstraConnector.
func (in *AstraConnector) DeepCopy() *AstraConnector {
	if in == nil {
		return nil
	}
	out := new(AstraConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AstraConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AstraConnectorList) DeepCopyInto(out *AstraConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AstraConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AstraConnectorList.
func (in *AstraConnectorList) DeepCopy() *AstraConnectorList {
	if in == nil {
		return nil
	}
	out := new(AstraConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AstraConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AstraConnectorSpec) DeepCopyInto(out *AstraConnectorSpec) {
	*out = *in
	out.Astra = in.Astra
	in.AstraConnect.DeepCopyInto(&out.AstraConnect)
	in.Neptune.DeepCopyInto(&out.Neptune)
	out.ImageRegistry = in.ImageRegistry
	out.AutoSupport = in.AutoSupport
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AstraConnectorSpec.
func (in *AstraConnectorSpec) DeepCopy() *AstraConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(AstraConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AstraConnectorStatus) DeepCopyInto(out *AstraConnectorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AstraConnectorStatus.
func (in *AstraConnectorStatus) DeepCopy() *AstraConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(AstraConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoSupport) DeepCopyInto(out *AutoSupport) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoSupport.
func (in *AutoSupport) DeepCopy() *AutoSupport {
	if in == nil {
		return nil
	}
	out := new(AutoSupport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRegistry) DeepCopyInto(out *ImageRegistry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRegistry.
func (in *ImageRegistry) DeepCopy() *ImageRegistry {
	if in == nil {
		return nil
	}
	out := new(ImageRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Neptune) DeepCopyInto(out *Neptune) {
	*out = *in
	in.ResourceRequirements.DeepCopyInto(&out.ResourceRequirements)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Neptune.
func (in *Neptune) DeepCopy() *Neptune {
	if in == nil {
		return nil
	}
	out := new(Neptune)
	in.DeepCopyInto(out)
	return out
}
