apiVersion: netapp.astraconnector.com/v1
kind: AstraConnector
metadata:
  name: astra-connector
  namespace: astra-connector
spec:
  natssync-client:
    image: natssync-client:2.0.202302011758
    cloud-bridge-url: <ASTRA_CONTROL_SERVICE_URL>
  nats:
    image: nats:2.6.1-alpine3.14
  httpproxy-client:
    image: httpproxylet:2.2.202310111117
  echo-client:
    image: echo-proxylet:2.0
  imageRegistry:
    name: theotw
    secret: otw-secret
  astra:
    token: <ASTRA_CONTROL_SERVICE_API_TOKEN>
    #clusterName: <PRIVATE_AKS_CLUSTER_NAME>
    accountId: <ASTRA_CONTROL_ACCOUNT_ID>
    acceptEULA: yes