apiVersion: astra.netapp.io/v1
kind: AstraConnector
metadata:
  name: astra-connector-operator
spec:
  connector:
    natssync-client:
      image: natssync-client:2.0
      cloud-bridge-url: https://astra.netapp.io
    nats:
      image: nats:2.6.1-alpine3.14
    astra:
      token: API Token from the API Access page in Astra UI
      accountId: Astra Account ID from the API Access page in Astra UI
  neptune:
    image: neptune:1.5
  imageRegistry:
    name: docker.repo.eng.netapp.com/oscarr/neptune

