apiVersion: apps/v1
kind: Deployment
metadata:
  name: astra-connector
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      containers:
      - name: astra-connector
        imagePullPolicy: Never