apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: astra-connector
subjects:
- kind: ServiceAccount
  name: astra-connector
  namespace: astra-connector
roleRef:
  kind: ClusterRole
  name: astra-connector
  apiGroup: rbac.authorization.k8s.io