apiVersion: apps/v1
kind: Deployment
metadata:
  name: astra-connector
  namespace: astra-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: astra-connector
  template:
    metadata:
      labels:
        deployment: astra-connector
    spec:
      containers:
      - name: astra-connector
        image: acs-image-registry.netapp.astra.io/astra-connector:latest
        env:
        - name: LOG_LEVEL
          value: "trace"
        resources:
          limits:
            cpu: 10m
            memory: 1280Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 20000
      serviceAccountName: astra-connector