//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 NetApp, Inc. All Rights Reserved.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Astra) DeepCopyInto(out *Astra) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Astra.
func (in *Astra) DeepCopy() *Astra {
	if in == nil {
		return nil
	}
	out := new(Astra)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AstraConnector) DeepCopyInto(out *AstraConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AstraConnector.
func (in *AstraConnector) DeepCopy() *AstraConnector {
	if in == nil {
		return nil
	}
	out := new(AstraConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AstraConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AstraConnectorList) DeepCopyInto(out *AstraConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AstraConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AstraConnectorList.
func (in *AstraConnectorList) DeepCopy() *AstraConnectorList {
	if in == nil {
		return nil
	}
	out := new(AstraConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AstraConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AstraConnectorSpec) DeepCopyInto(out *AstraConnectorSpec) {
	*out = *in
	out.NatssyncClient = in.NatssyncClient
	out.HttpProxyClient = in.HttpProxyClient
	out.EchoClient = in.EchoClient
	out.Nats = in.Nats
	out.Astra = in.Astra
	out.ImageRegistry = in.ImageRegistry
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AstraConnectorSpec.
func (in *AstraConnectorSpec) DeepCopy() *AstraConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(AstraConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AstraConnectorStatus) DeepCopyInto(out *AstraConnectorStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.NatssyncClient = in.NatssyncClient
	out.Astra = in.Astra
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AstraConnectorStatus.
func (in *AstraConnectorStatus) DeepCopy() *AstraConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(AstraConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AstraStatus) DeepCopyInto(out *AstraStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AstraStatus.
func (in *AstraStatus) DeepCopy() *AstraStatus {
	if in == nil {
		return nil
	}
	out := new(AstraStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EchoClient) DeepCopyInto(out *EchoClient) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EchoClient.
func (in *EchoClient) DeepCopy() *EchoClient {
	if in == nil {
		return nil
	}
	out := new(EchoClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpProxyClient) DeepCopyInto(out *HttpProxyClient) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpProxyClient.
func (in *HttpProxyClient) DeepCopy() *HttpProxyClient {
	if in == nil {
		return nil
	}
	out := new(HttpProxyClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRegistry) DeepCopyInto(out *ImageRegistry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRegistry.
func (in *ImageRegistry) DeepCopy() *ImageRegistry {
	if in == nil {
		return nil
	}
	out := new(ImageRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nats) DeepCopyInto(out *Nats) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nats.
func (in *Nats) DeepCopy() *Nats {
	if in == nil {
		return nil
	}
	out := new(Nats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatssyncClient) DeepCopyInto(out *NatssyncClient) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatssyncClient.
func (in *NatssyncClient) DeepCopy() *NatssyncClient {
	if in == nil {
		return nil
	}
	out := new(NatssyncClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatssyncClientStatus) DeepCopyInto(out *NatssyncClientStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatssyncClientStatus.
func (in *NatssyncClientStatus) DeepCopy() *NatssyncClientStatus {
	if in == nil {
		return nil
	}
	out := new(NatssyncClientStatus)
	in.DeepCopyInto(out)
	return out
}
