apiVersion: apps/v1
kind: Deployment
metadata:
  name: astra-connector
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: astra-connector
  template:
    metadata:
      labels:
        deployment: astra-connector
    spec:
      containers:
      - name: astra-connector
        image: ${IMAGE}
        env:
        - name: NATS_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: astra-connector-config-map
              key: nats_url
        - name: LOG_LEVEL
          value: "trace"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 10m
            memory: 1280Mi
        securityContext:
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000740000
      serviceAccountName: astra-connector-service-account