apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# At a minimum you need to include the set of base resources
# See the /deploy/samples/advanced for more kustomization options
resources:
- ../base