apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: astra-connector-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AstraConnector is the Schema for the astraconnectors API
      displayName: Astra Installer
      kind: AstraConnector
      name: astraconnectors.astra.netapp.io
      version: v1
  description: Astra Installer
  displayName: astra-connector-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - astra
  - neptune
  links:
  - name: Astra Installer
    url: https://astra-connector-operator.domain
  maturity: alpha
  provider:
    name: NetApp
    url: astra.netapp.io
  version: 0.0.0
