# permissions for end users to edit astraconnectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: astraconnector-editor-role
rules:
- apiGroups:
  - astra
  resources:
  - astraconnectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - astra
  resources:
  - astraconnectors/status
  verbs:
  - get
