// Code generated by mockery v2.19.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ClusterRegisterUtil is an autogenerated mock type for the ClusterRegisterUtil type
type ClusterRegisterUtil struct {
	mock.Mock
}

// GetConnectorIDFromConfigMap provides a mock function with given fields: cmData
func (_m *ClusterRegisterUtil) GetConnectorIDFromConfigMap(cmData map[string]string) (string, error) {
	ret := _m.Called(cmData)

	var r0 string
	if rf, ok := ret.Get(0).(func(map[string]string) string); ok {
		r0 = rf(cmData)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(cmData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterClusterWithAstra provides a mock function with given fields: astraConnectorId
func (_m *ClusterRegisterUtil) RegisterClusterWithAstra(astraConnectorId string) error {
	ret := _m.Called(astraConnectorId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(astraConnectorId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterNatsSyncClient provides a mock function with given fields:
func (_m *ClusterRegisterUtil) RegisterNatsSyncClient() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnRegisterNatsSyncClient provides a mock function with given fields:
func (_m *ClusterRegisterUtil) UnRegisterNatsSyncClient() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewClusterRegisterUtil interface {
	mock.TestingT
	Cleanup(func())
}

// NewClusterRegisterUtil creates a new instance of ClusterRegisterUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClusterRegisterUtil(t mockConstructorTestingTNewClusterRegisterUtil) *ClusterRegisterUtil {
	mock := &ClusterRegisterUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
