// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ClusterRegisterUtil is an autogenerated mock type for the ClusterRegisterUtil type
type ClusterRegisterUtil struct {
	mock.Mock
}

// GetAPITokenFromSecret provides a mock function with given fields: secretName
func (_m *ClusterRegisterUtil) GetAPITokenFromSecret(secretName string) (string, string, error) {
	ret := _m.Called(secretName)

	if len(ret) == 0 {
		panic("no return value specified for GetAPITokenFromSecret")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, string, error)); ok {
		return rf(secretName)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(secretName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(secretName)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(secretName)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IsClusterManaged provides a mock function with given fields:
func (_m *ClusterRegisterUtil) IsClusterManaged() (bool, string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsClusterManaged")
	}

	var r0 bool
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func() (bool, string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() string); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RegisterCloud provides a mock function with given fields:
func (_m *ClusterRegisterUtil) RegisterCloud() (string, string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RegisterCloud")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func() (string, string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() string); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RegisterCluster provides a mock function with given fields: cloudId, k8sServiceId
func (_m *ClusterRegisterUtil) RegisterCluster(cloudId string, k8sServiceId string) (string, string, error) {
	ret := _m.Called(cloudId, k8sServiceId)

	if len(ret) == 0 {
		panic("no return value specified for RegisterCluster")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (string, string, error)); ok {
		return rf(cloudId, k8sServiceId)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(cloudId, k8sServiceId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = rf(cloudId, k8sServiceId)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(cloudId, k8sServiceId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SetHttpClient provides a mock function with given fields: disableTls, astraHost
func (_m *ClusterRegisterUtil) SetHttpClient(disableTls bool, astraHost string) error {
	ret := _m.Called(disableTls, astraHost)

	if len(ret) == 0 {
		panic("no return value specified for SetHttpClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(bool, string) error); ok {
		r0 = rf(disableTls, astraHost)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClusterRegisterUtil creates a new instance of ClusterRegisterUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClusterRegisterUtil(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClusterRegisterUtil {
	mock := &ClusterRegisterUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
