// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SetWarning is an autogenerated mock type for the SetWarning type
type SetWarning struct {
	mock.Mock
}

// Execute provides a mock function with given fields: message
func (_m *SetWarning) Execute(message string) error {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSetWarning creates a new instance of SetWarning. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSetWarning(t interface {
	mock.TestingT
	Cleanup(func())
}) *SetWarning {
	mock := &SetWarning{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
