apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: ${NAMESPACE}
spec:
  serviceName: nats-cluster
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      serviceAccountName: nats-service-account
      containers:
      - name: nats
        image: nats:latest
        command:
        - "nats-server"
        - "--config"
        - "/etc/nats-config/nats.conf"
        ports:
        - name: client
          containerPort: 4222
        - name: cluster
          containerPort: 6222
        - name: monitor
          containerPort: 8222
        - name: metrics
          containerPort: 7777
        volumeMounts:
        - name: nats-config
          mountPath: /etc/nats-config
        - name: pid
          mountPath: /var/run/nats
        securityContext:
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000740000
      volumes:
      - name: nats-config
        configMap:
          name: nats-config
      - name: pid
        emptyDir: {}