apiVersion: netapp.astraagent.com/v1
kind: AstraAgent
metadata:
  name: astra-agent
spec:
  natssync-client:
    image: natssync-client:0.9.202202170408
  nats:
    image: nats:2.6.1-alpine3.14
  httpproxy-client:
    image: httpproxylet:0.9.202202170408
  echo-client:
    image: echo-proxylet:0.9.202202170408
  imageRegistry:
    name: theotw
  astra:
    token: nQeQPq065VWAq760PPULAizUDzrGweT3aCRR_-XA2q8=
    clusterName: ipsprintdemo
    accountId: 5831cf97-c52e-4185-ab83-db0fdd061c0e
    acceptEULA: yes