apiVersion: netapp.astraagent.com/v1
kind: AstraAgent
metadata:
  name: astra-agent
spec:
  natssync-client:
    image: natssync-client:0.9.202202170408
  nats:
    image: nats:2.6.1-alpine3.14
  httpproxy-client:
    image: httpproxylet:0.9.202202170408
  echo-client:
    image: echo-proxylet:0.9.202202170408
  imageRegistry:
    name: theotw
  astra:
    token: MyAstraToken
    clusterName: MyPrivateCluster
    accountId: MyAstraAccountID
    acceptEULA: yes