# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/astra.netapp.io_applications.yaml
- bases/astra.netapp.io_resourcebackups.yaml
- bases/astra.netapp.io_appvaults.yaml
- bases/astra.netapp.io_snapshots.yaml
- bases/astra.netapp.io_backups.yaml
- bases/astra.netapp.io_exechooks.yaml
- bases/astra.netapp.io_resticvolumebackups.yaml
- bases/astra.netapp.io_resticvolumerestores.yaml
- bases/astra.netapp.io_resourcerestores.yaml
- bases/astra.netapp.io_autosupportbundles.yaml
- bases/astra.netapp.io_exechooksruns.yaml
- bases/astra.netapp.io_snapshotrestores.yaml
- bases/astra.netapp.io_backuprestores.yaml
- bases/astra.netapp.io_resourcedeletes.yaml
- bases/astra.netapp.io_pvcerases.yaml
- bases/astra.netapp.io_backupinplacerestores.yaml
- bases/astra.netapp.io_schedules.yaml
- bases/astra.netapp.io_pvccopies.yaml
- bases/astra.netapp.io_snapshotinplacerestores.yaml
- bases/astra.netapp.io_appmirrorupdates.yaml
- bases/astra.netapp.io_appmirrorrelationships.yaml
- bases/astra.netapp.io_resourcesummaryuploads.yaml
- bases/astra.netapp.io_autosupportbundleschedules.yaml
- bases/astra.netapp.io_shutdownsnapshots.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_applications.yaml
#- patches/webhook_in_resourcebackups.yaml
#- patches/webhook_in_appvaults.yaml
#- patches/webhook_in_snapshots.yaml
#- patches/webhook_in_backups.yaml
#- patches/webhook_in_exechooks.yaml
#- patches/webhook_in_resticvolumebackups.yaml
#- patches/webhook_in_resticvolumerestores.yaml
#- patches/webhook_in_resourcerestores.yaml
#- patches/webhook_in_autosupportbundles.yaml
#- patches/webhook_in_exechooksruns.yaml
#- patches/webhook_in_snapshotrestores.yaml
#- patches/webhook_in_backuprestores.yaml
#- patches/webhook_in_resourcedeletes.yaml
#- patches/webhook_in_pvcerases.yaml
#- patches/webhook_in_backupinplacerestores.yaml
#- patches/webhook_in_schedules.yaml
#- patches/webhook_in_pvccopies.yaml
#- patches/webhook_in_snapshotinplacerestores.yaml
#- patches/webhook_in_appmirrorupdates.yaml
#- patches/webhook_in_appmirrorrelationships.yaml
#- patches/webhook_in_resourcesummaryuploads.yaml
#- patches/webhook_in_autosupportbundleschedules.yaml
#- patches/webhook_in_shutdownsnapshots.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_applications.yaml
#- patches/cainjection_in_resourcebackups.yaml
#- patches/cainjection_in_appvaults.yaml
#- patches/cainjection_in_snapshots.yaml
#- patches/cainjection_in_backups.yaml
#- patches/cainjection_in_exechooks.yaml
#- patches/cainjection_in_resticvolumebackups.yaml
#- patches/cainjection_in_resticvolumerestores.yaml
#- patches/cainjection_in_resourcerestores.yaml
#- patches/cainjection_in_autosupportbundles.yaml
#- patches/cainjection_in_exechooksruns.yaml
#- patches/cainjection_in_snapshotrestores.yaml
#- patches/cainjection_in_backuprestores.yaml
#- patches/cainjection_in_resourcedeletes.yaml
#- patches/cainjection_in_pvcerases.yaml
#- patches/cainjection_in_backupinplacerestores.yaml
#- patches/cainjection_in_schedules.yaml
#- patches/cainjection_in_pvccopies.yaml
#- patches/cainjection_in_snapshotinplacerestores.yaml
#- patches/cainjection_in_appmirrorupdates.yaml
#- patches/cainjection_in_appmirrorrelationships.yaml
#- patches/cainjection_in_resourcesummaryuploads.yaml
#- patches/cainjection_in_autosupportbundleschedules.yaml
#- patches/cainjection_in_shutdownsnapshots.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
