
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-astra-netapp-io-v1-astraconnector
  failurePolicy: Fail
  name: mastraconnector.kb.io
  rules:
  - apiGroups:
    - astra.netapp.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - astraconnectors
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-astra-netapp-io-v1-astraconnector
  failurePolicy: Fail
  name: astraconnector.kb.io
  rules:
  - apiGroups:
    - astra.netapp.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - astraconnectors
  sideEffects: None
