apiVersion: apps/v1
kind: Deployment
metadata:
  name: astra-connector
  namespace: astra-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: astra-connector
  template:
    metadata:
      labels:
        deployment: astra-connector
    spec:
      containers:
      - name: astra-connector
        image: cr.netapp.astra.io/astra-connector:latest
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: NATS_DISABLED
          value: "false"

        - name: API_TOKEN_SECRET_REF
          value: "astra-api-token"
        - name: ASTRA_CONTROL_URL
          value: ""
        - name: ACCOUNT_ID
          value: ""
        - name: CLOUD_ID
          value: ""
        - name: CLUSTER_ID
          value: ""

        - name: HOST_ALIAS_IP
          value: ""
        - name: SKIP_TLS_VALIDATION
          value: "false"
        - name: MEMORY_RESOURCE_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: astra-connector
              resource: limits.memory

        resources:
          limits:
            cpu: 10m
            memory: 1280Mi
        securityContext:
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000740000
      serviceAccountName: astra-connector
