apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: astra-connector
  namespace: astra-connector
subjects:
- kind: ServiceAccount
  name: astra-connector
  namespace: astra-connector
roleRef:
  kind: Role
  name: astra-connector
  apiGroup: rbac.authorization.k8s.io