apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: astra-connector
  namespace: astra-connector
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "delete", "watch", "list", "get"]
- apiGroups: ["astra.netapp.io"]
  resources: [
    "applications",
    "appmirrorrelationships",
    "appmirrorupdates",
    "appvaults",
    "autosupportbundles",
    "backups",
    "backupinplacerestores",
    "backuprestores",
    "exechooks",
    "exechooksruns",
    "pvccopies",
    "pvcerases",
    "resourcebackups",
    "resourcedeletes",
    "resourcerestores",
    "resourcesummaryuploads",
    "resticvolumebackups",
    "resticvolumerestores",
    "schedules",
    "shutdownsnapshots",
    "snapshots",
    "snapshotinplacerestores",
    "snapshotrestores",
    "astraconnectors",
    "autosupportbundleschedules",
    "kopiavolumebackups",
    "kopiavolumerestores"
  ]
  verbs: ["create", "update", "delete", "watch", "list", "get"]
