
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: astra-connector-operator
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - apiextensions.k8s.io
  - apps
  - autoscaling
  - batch
  - crd.projectcalico.org
  - extensions
  - networking.k8s.io
  - policy
  - rbac.authorization.k8s.io
  - security.openshift.io
  - snapshot.storage.k8s.io
  - storage.k8s.io
  - trident.netapp.io
  resources:
  - configmaps
  - cronjobs
  - csidrivers
  - csinodes
  - customresourcedefinitions
  - daemonsets
  - deployments
  - horizontalpodautoscalers
  - ingresses
  - jobs
  - namespaces
  - networkpolicies
  - persistentvolumeclaims
  - poddisruptionbudgets
  - pods
  - podsecuritypolicies
  - podtemplates
  - replicasets
  - replicationcontrollers
  - replicationcontrollers/scale
  - rolebindings
  - roles
  - secrets
  - securitycontextconstraints
  - serviceaccounts
  - services
  - statefulsets
  - storageclasses
  - tridentbackends
  - tridentmirrorrelationships
  - tridentnodes
  - tridentsnapshotinfos
  - tridentversions
  - tridentvolumes
  - volumesnapshotcontents
  - volumesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - use
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - astra.netapp.io
  resources:
  - astraconnectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - astra.netapp.io
  resources:
  - astraconnectors/finalizers
  verbs:
  - update
- apiGroups:
  - astra.netapp.io
  resources:
  - astraconnectors/status
  verbs:
  - get
  - patch
  - update
