apiVersion: cache.astraagent.com/v1
kind: AstraAgent
metadata:
  name: astra-agent
spec:
  namespace: astra-agent
  natssync-client:
    name: natssync-client
    size: 1
    image: theotw/natssync-client:0.9.202201132025
    cloud-bridge-url: https://integration.astra.netapp.io
    port: 8080
    nodeport: 31000
    protocol: TCP
  nats:
    name: nats
    cluster-service-name: nats-cluster
    size: 2
    image: nats:2.6.1-alpine3.14
    client-port: 4222
    cluster-port: 6222
    monitor-port: 8222
    metrics-port: 7777
    gateways-port: 7522
  httpproxy-client:
    name: httpproxy-client
    size: 1
    image: theotw/httpproxylet:0.9.202201132025
  echo-client:
    name: echo-client
    size: 1
    image: theotw/echo-proxylet:0.9.202201132025
  configMap:
    name: natssync-client-configmap
    rolename: natssync-client-configmap-role
    rolebindingname: natssync-client-configmap-rolebinding
    serviceaccountname: natssync-client-configmap-serviceaccount
  astra:
    register: true
    token: jiw948Fusiqd0fwfKNb9hDdcaf-dbuWmKkUaxG2fNKU=
    clusterName: ipsprintdemo