apiVersion: apps/v1
kind: Deployment
metadata:
  name: astra-connector
  namespace: astra-connector
spec:
  template:
    spec:
      containers:
      - name: astra-connector
        # Example: Use a custom image registry and tag
        image: my.image.registry.com/path/astra-connector:latest
      imagePullSecrets:
        # Example: Use a kustomize-generated image pull secret
        # You could alternatively reference a pre-existing secret in the target namespace
      - name: my-image-registry-secret