apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd
- manager
- rbac

# ToDo: remove this once neptune code is updated to not have hardcoded references to job resource names that include this prefix
#namePrefix: neptune-
