---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: autosupportbundle
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - '*'
  resourceNames:
  - kube-system
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - '*'
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - '*'
  resources:
  - pods/log
  verbs:
  - get
